name: flutter_map_tappable_polyline
description: A flutter_map plugin that adds Polyline class with onTap event
version: 3.5.0
homepage: https://github.com/OwnWeb/flutter_map_tappable_polyline
publish_to: https://unpub.optyce.eu

environment:
  sdk: ">=2.12.0 <=3.0.0"
  flutter: ">=2.12.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map:
    hosted:
      name: flutter_map
      url: https://unpub.optyce.eu
    version: ^0.15.1
  latlong2: ^0.8.1
  positioned_tap_detector_2: ^1.0.0

dev_dependencies:
  pedantic: ^1.11.1
